version: "3.9"

services:
  app:
    build:
      context: . # build docker image inside current directory
      args:
        - DEV=true # include dev-dependencies
    ports:
      - "8000:8000" # connect local:container ports
    volumes:
      - ./app:/app # map local:container directories (syncs real-time updates)
      - dev-static-data:/vol/web # mapping to static directory

    # default docker-compose command
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    # set up environment variables (used by app's settings.py)
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1

    # set up connection between services
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
  dev-static-data:
