---
name: Checks

on: [push] # trigger

jobs:
  # job name
  test-lint:
    # user-friendly name (what actually displays online)
    name: Test and Lint

    # CI runner
    runs-on: ubuntu-20.04

    # job specs
    steps:
      # authenticate with dockerhub to avoid rate limits
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # checkout code (optional in general, but necessary to test/lint)
      - name: Checkout
        uses: actions/checkout@v2

      # testing job
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      # linting job
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
